name: beam_drop
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.4.0
  permission_handler: ^12.0.0+1
  file_picker: ^10.1.9
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  network_info_plus: ^6.1.4
  file_selector: ^1.0.3
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2          # доступ к «Фото» (iOS и Android)
  # image_gallery_saver: ^2.0.3   # сохраняем картинки в Camera Roll (iOS)
  saver_gallery: ^4.0.1
#  downloads_path_provider_28: ^0.1.2
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  signals: ^6.0.2
  signals_flutter: ^6.0.2
  open_filex: ^4.7.0
  flutter_nsd: ^1.6.0
  auto_route: ^10.0.1

  nsd: any
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4

  flutter_test:
    sdk: flutter
  freezed: ^3.0.6

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: any
  auto_route_generator: ^10.0.1
  injectable_generator: ^2.7.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/foreground.png"
  adaptive_icon_background: "assets/background.png"
  adaptive_icon_foreground: "assets/foreground.png"
  windows:
    generate: true
    image_path: "assets/main_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/rounded_main_logo.png"

flutter:
  uses-material-design: true


  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

